name: zegocloud_uikit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  toastification: ^3.0.2
  gap: ^3.0.1

  queen_validators: ^1.0.1
  country_pickers: ^3.0.1
  flutter_libphonenumber: ^2.5.1

  # Tools packages
  device_info_plus: ^11.4.0
  shared_preferences: ^2.2.3

  # ZegoCloud UIkit
  zego_uikit_signaling_plugin: ^2.8.2
  zego_uikit_prebuilt_call: ^4.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true